### PR TITLE
Initial Splunk code donation

### PR DESCRIPTION
**Pull request by breedx-splk**
I merged from the original repo to retain full revision history.  Replaced all the references to splunk and picked a new package namespace: `io.opentelemetry.android`. Confirmed that an `.aar` is built, although the name is probably incorrect. 

There's definitely a lot more to do after this. 😁

### CODE REVIEW

**Review by LikeTheSalad — APPROVED** [review]
Nice! I didn't take a detailed look at everything because we're going to work on changing a lot after this is merged anyway so... ✅

**Comment by breedx-splk** [comment]
Bumping to try and get status to clear.

**Comment by breedx-splk** [comment]
once more with gusto

**Comment by breedx-splk** [comment]
Ok, have opened https://github.com/open-telemetry/community/issues/1621 as requested by GC.

**Pull request merged**
