### PR TITLE
Allow user to customize propagators

### PR DESCRIPTION
**Pull request by breedx-splk**
Relates to #56.

This adds two new methods to the `OpenTelemetryRumBuilder`: 

* `setPropagator(TextMapPropagator)` - replaces all configured propagators with the given one
* `addPropagator(TextMapPropagator)` - adds the propagator to the collection of configured propagators to use in the sdk

This also defaults the propagators to the same ones as the upstream sdk -- `W3CTraceContextPropagator` and `W3CBaggagePropagator`.

### CODE REVIEW

**Review by trask — COMMENTED** [review]
does it make sense to align this with `AutoConfiguredOpenTelemetrySdkBuilder` and introduce `addPropagatorCustomizer` instead?

**Comment by breedx-splk** [comment]
> does it make sense to align this with `AutoConfiguredOpenTelemetrySdkBuilder` and introduce `addPropagatorCustomizer` instead?

Oh yeah probably. I wish @GerardPaligot  would also chime in, but I'll take a stab at it to see how that looks.

**Comment by breedx-splk** [comment]
Oh, I'm seeing now that  @GerardPaligot commented in the issue. Well, I hope the change to use a propagator customizer is also suitable. 🤞🏻

**Review by LikeTheSalad — APPROVED** [review]
I think both approaches are fine tbh, though I'm always up to keep consistency across similar/related tools whenever possible.

**Pull request merged**
